version: '3.8'

services:
  # --- PHP-FPM Service ---
  php:
    build:
      context: ./docker/php
    container_name: symfony_php-t228-1
    volumes:
      - ./app:/var/www/symfony:cached
    depends_on:
      - database

  # --- Nginx Web Server ---
  nginx:
    image: nginx:alpine
    container_name: symfony_nginx-t228-1
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/symfony:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  # --- MySQL Database ---
  database:
    image: mysql:8.0
    container_name: symfony_db-t228-1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "33060:3306" # Expose on a diff port to avoid conflict with local MySQL
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: